/**
 * This file is auto-generated by Firebase AI Studio.
 * Do not edit it manually.
 */
import type { Timestamp } from 'firebase/firestore';

export type Step = {
  description: string;
  status: 'pending' | 'completed' | 'failed';
  log?: string;
  action: string;
  parameters?: Record<string, any>;
};

export type Task = {
  id: string;
  goal: string;
  status: 'in-progress' | 'completed' | 'failed';
  progress: number;
  steps: Step[];
  createdAt: Timestamp;
};

export type Alert = {
  id: string;
  title: string;
  description: string;
  severity: 'high' | 'medium' | 'low';
  timestamp: Timestamp;
};

export type System = {
    id: string;
    name: string;
    status: 'online' | 'offline' | 'degraded';
    cpuUsage: number;
    memoryUsage: number;
};

export type Report = {
  id: string;
  taskId: string;
  report: string;
  generatedAt: Timestamp;
}
