// This file is auto-generated by the Firebase CLI.
// Do not edit it manually.
export const firebaseConfig = {
  "apiKey": "dummy-key",
  "authDomain": "dummy-domain.firebaseapp.com",
  "projectId": "dummy-proj",
};
